[package]
name = "ghaction_version_gen"
description = "Generate various version options as github action outputs"
version = "0.13.6"
authors = ["Leandro Lisboa Penz <lpenz@lpenz.org>"]
edition = "2021"
license = "MIT"
readme = "README.md"
repository = "https://github.com/lpenz/ghaction-version-gen"
categories = ["command-line-utilities"]
keywords = ["github-action", "version-generate"]

[dependencies]
clap = { version = "4.4.11", features = ["derive"] }
regex = "1.10.2"
anyhow = "1.0.76"
toml = "0.8.8"
configparser = "3.0.3"

[dev-dependencies]
tempfile = "3.8.1"
