[package]
name = "ghaction_version_gen"
description = "Generate various version options as github action outputs"
version = "0.14.0"
authors = ["Leandro Lisboa Penz <lpenz@lpenz.org>"]
edition = "2021"
license = "MIT"
readme = "README.md"
repository = "https://github.com/lpenz/ghaction-version-gen"
categories = ["command-line-utilities"]
keywords = ["github-action", "version-generate"]

[dependencies]
clap = { version = "4.5.1", features = ["derive"] }
regex = "1.10.3"
anyhow = "1.0.79"
toml = "0.8.10"
configparser = "3.0.4"

[dev-dependencies]
tempfile = "3.10.0"
