[package]
name = "ghaction_version_gen"
description = "Generate various version options as github action outputs"
version = "0.13.2"
authors = ["Leandro Lisboa Penz <lpenz@lpenz.org>"]
edition = "2021"
license = "MIT"
readme = "README.md"
repository = "https://github.com/lpenz/ghaction-version-gen"
categories = ["command-line-utilities"]
keywords = ["github-action", "version-generate"]

[dependencies]
clap = { version = "4.1.8", features = ["derive"] }
regex = "1.7.1"
anyhow = "1.0.69"
toml = "0.7.2"
configparser = "3.0.2"

[dev-dependencies]
tempfile = "3.4.0"
